logging:
  level:
    root: INFO
    org.springframework.web: INFO

spring.data:
    mongodb:
      host: ms-customers-db
      username: customers-user
      password: pwd123456!
      port: 27017
      database: db
      authentication-database: admin