
logging:
  cloud.csonic.mscustomers: INFO

microservice:
  inPanic: false
  name: ms-customers
  jwt:
    key: abc123456789012345678901234567890
  correlations:
    url: http://msapplications-ktl:8080

spring:
  kafka:
    template:
      default-topic: customers
    producer:
      bootstrap-servers: kafka01:9092,kafka02:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      # properties:
      #   ack: all
      #   retries: 10
      #   retry.backoff.ms: 1000
      properties:
        ack: all
        retries: 2147483647
        retry.backoff.ms: 1000
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        compression.type: snappy
        linger.ms: 5
        batch.size: 32768        
    consumer:
      bootstrap-servers: kafka01:9092,kafka02:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: customers
    # admin:
    #   properties:
    #     bootstrap.servers: kafka01:9092,kafka02:9092