
logging:
  com:
    learnkafka:
      producer: INFO

microservice:
  inPanic: true
  name: ms-events
  jwt:
    key: abc123456789012345678901234567890
  correlations:
    url: http://localhost:8080


spring:
  data.mongodb:
    host: msevents-db
    username: events-user
    password: pwd123456!
    port: 27017
    database: db
    authentication-database: admin
  kafka:
    template:
      default-topic: customers
    producer:
      bootstrap-servers: kafka01:9092,kafka02:9093,kafka03:9092,kafka04:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        ack: all
        retries: 10
        retry.backoff.ms: 1000
    consumer:
      bootstrap-servers: kafka01:9092,kafka02:9093,kafka03:9092,kafka04:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: events
    admin:
      properties:
        bootstrap.servers: kafka01:9092,kafka02:9093,kafka03:9092,kafka04:9092