
logging:
  com:
    learnkafka:
      producer: INFO

microservice:
  inPanic: true
  name: ms-notifications
  jwt:
    key: abc123456789012345678901234567890
  realtime:
    url: https://fir-demo-8b4c6-default-rtdb.firebaseio.com/
  fireBaseServiceAccount: /service-account.json

spring:
  kafka:
    template:
      default-topic: notifications
    producer:
      bootstrap-servers: kafka01:9092,kafka02:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        ack: all
        retries: 10
        retry.backoff.ms: 1000
    consumer:
      bootstrap-servers: kafka01:9092,kafka02:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: notifications